from shapely.geometry import Point


def AddCoordinatesToGridCellBasedHotspots(Hotspot: list, xx: list, yy: list):
    """This function takes the point based cell based hotspots generated using hotspot generation module using
    BFS_of_Cells and add coordinates having latitude longitude pair from the main grid.

        Parameters
        ----------
        Hotspots: list
            The grid point based hotspots generated by the BFS method
        xx : list
            X axis lists from the numpy meshgrid
        yy : list
            Y axis lists from the numpy meshgrid

        Returns
        -------
        list of list
            the hotspots list, where the initial point of the cell is converted into middle point of the cell and
            each point is represented by their latitude longitude pairs
        """
    newHotspot = []
    for point in Hotspot:
        #  Find the coordinates of the four points of the cell and calculate middle point of cell coordinate
        coordinate = Point((xx[point[0]][0] + xx[point[0]+1][0])/2 , (yy[0][point[1]] + yy[0][point[1]+1])/2)
        newHotspot.append(coordinate)


    return  newHotspot